eureka:
  client:
    fetchRegistry: true
    instance:
      preferIpAddress: true
    registerWithEureka: true
    service-url:
      defaultZone: http://localhost:8081/eureka
  instance:
    hostname: localhost
server:
  port: 8080
spring:
  application:
    name: gateway-service
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
    web-application-type: reactive
zuul:
  ignoredServices: '*'
  sensitiveHeaders: Cookie, Set-Cookie
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  routes:
    category-service:

      url: http://localhost:8082
      stripPrefix: false
    gateway-service:
      path: /gateway-service/**
      serviceId: gateway-service
      stripPrefix: false
