eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
    service-url:
      defaultZone: http://localhost:8081/eureka
  instance:
    hostname: localhost
server:
  port: 8081
spring:
  application:
    name: discovery-service